spring.application.name=inventoryMS
server.servlet.context-path=/inventoryMS
server.port=8083

### DATABASE ###
spring.data.mongodb.uri=mongodb://localhost:27017/inventorydb

spring.docker.compose.enabled=false


### JPA / HIBERNATE ###
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
logging.level.root= INFO
logging.level.tn.esprit.spring.service= INFO
logging.logback.rollingpolicy.max-file-size= 100KB
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{60} - %msg %n
logging.pattern.file= %msg %n
logging.file.name=c:/logging/spring_file.log

